### ISSUE TITLE
Disable es-x/no-resizable-and-growable-arraybuffers

### ISSUE THREAD

**Issue by edg2s** [wikimedia/jscs-preset-wikimedia#555]
User methods called `resize` are common. `ArrayBuffer#resize` from ES2024 is unlikely to be used.

This rule is going to trigger too many false positives.

**Comment by supertassu** [comment]
I'm not sure why but just adding this to `.eslintrc.json` in a specific repository does not work:
```json
{
	"rules": {
		"es-x/no-resizable-and-growable-arraybuffers": "off"
	}
}
```
This is breaking LibUp on some repositories.

**Comment by jdforrester** [comment]
> I'm not sure why but just adding this to `.eslintrc.json` in a specific repository does not work:
> 
> ```json
> {
> 	"rules": {
> 		"es-x/no-resizable-and-growable-arraybuffers": "off"
> 	}
> }
> ```
> 
> This is breaking LibUp on some repositories.

Can you link to a repo where that's the case? I just fixed this manually _e.g._ in https://gerrit.wikimedia.org/r/c/mediawiki/extensions/AbuseFilter/+/997854 and it seemed to work. But yes, we should fix this.

**Comment by supertassu** [comment]
> Can you link to a repo where that's the case?

I saw this in AbuseFilter after LibUp's automatic disabling logic did not work there.

**Comment by NovemLinguae** [comment]
I tried patching PageTriage eslint-config-wikimedia to latest version, but am still getting a `es-x/no-resizable-and-growable-arraybuffers` error in CI. Any idea what I did wrong?

https://gerrit.wikimedia.org/r/c/mediawiki/extensions/PageTriage/+/1021475

**Comment by sohomdatta1** [comment]
It seems like `vue3/es6.js` (the module for linting vue3 .vue files) does not include `./client/common.json` config where this rule was added. Maybe that's why the error shows up ? (I might be wrong tho!)

**Comment by edg2s** [comment]
The rule was incorrectly added to common.json, which is before the language rules (es-x/...) get loaded.
